sonar.projectKey=pipeline_project
sonar.projectName=pipeline_project
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,tardis/**,brouillon/**,audio/**,.git/**,.github/**,*.tar
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=coverage/lcov.info