on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install test environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '20'

      - name: Validate the HTML syntax
        run: npx htmlhint "**/*.html"

      - name: Validate the JavaScript syntax
        run: find . -name "*.js" -not -path "*/node_modules/*" -exec node --check {} \;

  check_security:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Requis par SonarQube

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true

      - name: Scan du système de fichiers avec Trivy
        uses: aquasec/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1' # Bloque le pipeline en cas de vulnérabilité
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'



  build:
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - name: Récupérer le code du projet
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Construire l'image Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: mon-site-html:latest
      
      - name: Exporter l'image en fichier tar
        run: docker save mon-site-html:latest -o /tmp/mon-site-html.tar

      - name: Uploader l'image Docker en artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/mon-site-html.tar

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Télécharger l'image Docker archivée
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Récupérer l'IP locale du runner
        id: local_ip
        run: |
          RUNNER_IP=$(hostname -I | awk '{print $1}')
          echo "L'adresse IP locale de ce runner est : $RUNNER_IP"
          echo "ip=$RUNNER_IP" >> $GITHUB_OUTPUT

      - name: Charger l'image Docker
        run: docker load --input /tmp/mon-site-html.tar

      - name: Nettoyer un ancien conteneur éventuel
        run: |
          docker stop conteneur-site 2>/dev/null || true
          docker rm conteneur-site 2>/dev/null || true

      - name: Déployer et démarrer le conteneur
        run: |
          docker run -d \
            -p 0.0.0.0:8080:80 \
            --name conteneur-site \
            mon-site-html:latest

      - name: Valider l'accès via l'IP et le Port
        run: |
          sleep 3
          echo "Site accessible sur : http://${{ steps.local_ip.outputs.ip }}:8080"
          curl -v http://${{ steps.local_ip.outputs.ip }}:8080

