on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install test environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate the HTML syntax
        run: npx htmlhint "**/*.html"

      - name: Validate the JavaScript syntax
        run: find . -name "*.js" -not -path "*/node_modules/*" -exec node --check {} \;

  build:
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - name: Récupérer le code du projet
        uses: actions/checkout@v4

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construire l'image Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: mon-site-html:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Production Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # Le point '.' signifie qu'on prend tout le contenu de la racine du projet
          path: '.' 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

